version: 0.2

phases:
  build:
    commands:
      - echo Creating imagedefinitions.json for Backend...
      - printf '[{"name":"Main","imageUri":"%s"}]' "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$BACKEND_REPOSITORY:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json